exclude: ^.*(.min.js|.min.css)$
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-yaml
        args: ["--unsafe"] # because of tags in mkdocs.yml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.0-alpha.6
    hooks:
      - id: prettier
        files: \.(css|less|md|json|sql)$
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.36.0
    hooks:
      - id: eslint
        additional_dependencies:
          - eslint-config-prettier@9.1.0
          - eslint-plugin-prettier@5.1.3
          - eslint-plugin-jsdoc@48.2.1
        args: ["--fix"]
